# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactProtoDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'SwiftProtobuf', '~> 1.0'

  # Pods for ContactProtoDemo

  target 'ContactProtoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ContactProtoDemoUITests' do
    # Pods for testing
  end

end
